name: build pages
on:
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version: 12.x
      - name: Install Dependencies
        run: npm ci --production
      - name: Build pages
        # run lint & diag & build:run with shell instead of 'npm run build',
        # to keep 'npm-run-all' out of prod-dependencies
        run: npm run lint && npm run diag && npm run build:run
      - name: fix script tag
        run: sed -i "s/xcript/script/g" dist/index.html
      - name: inject GA ID
        run: sed -i "s/GA_TRACKING_ID/$GA_TRACKING_ID/g" dist/index.html
        env:
          GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
