name: build pages
on:
  push:
    branches: master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.4.3
        with:
          version: 14.x
      - name: Install Dependencies
        run: npm ci
      - name: Build pages
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
        if: github.ref == 'refs/heads/master'
